name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: stackct.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kubot:latest
